version: "3"

services:
    pgdb:
        image: postgres
        container_name: pgdb
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_DB: admintory
            POSTGRES_PASSWORD: root
    server:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        links: 
            - pgdb
        restart: always